source 'https://rubygems.org'

gem 'jekyll'
gem 'rack-jekyll'
gem 'RedCloth'
gem 'rack-contrib'
gem 'rack-rewrite'
gem 'rdiscount'
gem 'thin'
gem 'jekyll-asset-pipeline'
gem 'coffee-script'
gem 'sass'
